name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, macOS, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Check Python syntax
        run: |
          python -m py_compile app/app.py

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t local-devops-cicd:${{ github.sha }} .

      - name: Tag Docker image for Floci ECR
        run: |
          docker tag local-devops-cicd:${{ github.sha }} \
          localhost:5100/000000000000/us-east-1/local-devops-app:${{ github.sha }}

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t local-devops-cicd:${{ github.sha }} .

      - name: Tag Docker image for Floci ECR
        run: |
         docker tag local-devops-cicd:${{ github.sha }} \
         localhost:5100/000000000000/us-east-1/local-devops-app:${{ github.sha }}

      - name: Push Docker image to Floci ECR
        run: |
         docker push localhost:5100/000000000000/us-east-1/local-devops-app:${{ github.sha }}